### ISSUE TITLE
function multiselect in windows return index as options but in ubuntu returns value of options

### ISSUE THREAD

**Issue by HusseinIbrahem** [laravel/prompts#178] opened 2024-12-14 08:02 UTC
### Laravel Prompts Version

0.1.25

### Laravel Version

10.48.23

### PHP Version

8.2

### Operating System & Version

windows 10 , ubutnu 

### Terminal Application

power shel

### Description

this code :
```
$folders = multiselect(
            label: 'select folders.',
            options: $uploadDirectories,
            required: true,
        );
```
in windows returns key of selected but in ubuntu returns the values nad i have to write this code to prevent any error in any operating system:
```
if (is_numeric($folders[0])) {
            $this->selectedDirectories = array_values(array_intersect_key(
                $uploadDirectories,
                array_flip($folders)
            ));
        }
        else {
            $this->selectedDirectories = $folders;
        }
```

### Steps To Reproduce

nothing

**Comment by jessarcher** [comment] 2024-12-14 12:47
What type of keys does `$uploadDirectories` have? Are they strings or integers? If integers, are they sequential starting from 0?

**Comment by HusseinIbrahem** [comment] 2024-12-14 15:12
hello, $uploadDirectories have string values of paths like:
upload/users,
upload/profiles,
...
in ubuntu returns value path and in windows returns index of values
thank you for this package.

**Comment by jessarcher** [comment] 2024-12-16 06:51
I'm having trouble replicating this one. When you say Windows, are you talking about native Windows (i.e. `php.exe`) or WSL? I'm assuming you're talking about native Windows where Prompts falls back to Symfony console components.

To try to replicate this, I've created a command with the following:

```php
<?php

dump(
    multiselect('test', [
        'upload/users',
        'upload/profiles',
    ], required: true)
);

Prompt::fallbackWhen(true); // Simulate running on Windows using the Symfony console fallback.

dump(
    multiselect('test', [
        'upload/users',
        'upload/profiles',
    ], required: true)
);
```

When running the command, I tried selecting all possible combinations (the first option, the second option, and both options) and always received the values:

![image](https://github.com/user-attachments/assets/16983328-94ba-4e5e-86ca-37d06b849bdc)

Are you sure the array you pass in has sequential numeric keys starting from 0? If you pass it through `array_filter()`, then it may not have sequential keys any longer, in which case Prompts and the Symfony fallback should return the key instead of the value.

**Comment by HusseinIbrahem** [comment] 2024-12-16 11:00
Hi, i'm talking about native Windows. i'm using `nwidart/laravel-modules` package, i'm write this code in command 
```
        $a = [
            'upload/users',
            'upload/profiles',
        ];
        dump($a);
        dump(
            multiselect('test', $a, required: true)
        );

        Prompt::fallbackWhen(true); // Simulate running on Windows using the Symfony console fallback.

        dump(
            multiselect('test', $a, required: true)
        );
```
and the output is same:
![image](https://github.com/user-attachments/assets/3f35b22c-1144-4906-8f61-34891881ee6b)
also run this code in laravle command without module package and the result is same. my best regards.

**Comment by jessarcher** [comment] 2024-12-16 23:16
Thanks @HusseinIbrahem.

I've just realised the problem is with the older version of Laravel you're using.

This issue was fixed in the following PRs:

* https://github.com/laravel/framework/pull/50995
* https://github.com/laravel/framework/pull/51078

Upgrading to the latest version of Laravel should fix the issue for you.

**Closed by jessarcher** 2024-12-16 23:16 UTC
