### ISSUE TITLE
Validation message cut off at the last character.

### ISSUE THREAD

**Issue by henzeb** [laravel/prompts#126] opened 2024-03-17 12:57 UTC
### Laravel Prompts Version

0.1.16

### Laravel Version

0

### PHP Version

8.2

### Operating System & Version

Kubuntu 22.04

### Terminal Application

Konsole, Yakuake

### Description

See below. Any message below the box is cut off. 

![Screenshot_20240317_134950](https://github.com/laravel/prompts/assets/15928532/db650602-d672-483c-96e9-dc6a85ec78f6)

### Steps To Reproduce

just create a test prompt in a script where composers autoload is loaded:
```php
text('email', validate: function () {
    return 'Invalid emailaddress';
});
```

Just press enter. 

I have not added a laravel version, but it is broken there as well.

**Comment by jessarcher** [comment] 2024-03-17 13:07
Hi @henzeb,

I'm unable to replicate this using Konsole on Fedora:

![image](https://github.com/laravel/prompts/assets/4977161/de689b3d-0dcc-4e3b-9b38-e96c5b173b8e)

I also don't see how it would be possible for this library to be the cause of this as terminals don't provide that level of control.

Can you try a different font and see if that might be causing it?

**Comment by henzeb** [comment] 2024-03-17 16:35
The default font is named Hack. Changing the font does have some effect. But it changes the overall appearance and most is just making things look ugly.

what's the font Fedora is using for Konsole?

**Comment by jessarcher** [comment] 2024-03-18 00:16
> what's the font Fedora is using for Konsole?

The default is set to "Monospace", which I assume just resolves to the system monospace default. I'm using Gnome, so I'm not sure what default it's using.

I just installed Hack from https://sourcefoundry.org/hack/ and configured it in Konsole, but still can't replicate the issue:

![image](https://github.com/laravel/prompts/assets/4977161/5575ff17-ab1c-44ef-a982-d8a587d7b677)

I also tried it with JetBrains Mono:

![image](https://github.com/laravel/prompts/assets/4977161/e2a1ce49-dea9-4e2e-a19e-af3a990684f7)

I suspect this is an issue with font rendering on your system. Prompts has little control over the rendering other than specifying characters and basic styling of things like colours.

In your screenshot, the warning symbol ([Unicode U+26A0](https://en.wikipedia.org/wiki/Miscellaneous_Symbols)) looks like it's rendering wider than a single monospace character. That may be throwing off the way that your terminal calculates the width of the line, causing the cropping.

You could try replicating this by running the following commands:

```sh
echo "⚠ Invalid email address"
echo "Invalid email address"
```

There's also the possibility that the colours trigger some weird behaviour, so you might like to try including them too:

```sh
echo "\e[33m⚠ Invalid email address"
echo "\e[33mInvalid email address"
```

I will close this for now, as I don't think it's an issue with Prompts. Feel free to re-open if you can confirm that Prompts is specifically causing it. We could look at removing the warning symbol if it's triggering terminal bugs, but I'd want to see widespread reports before going that far.

**Closed by jessarcher** 2024-03-18 00:16 UTC
Labels: needs more info

**Comment by henzeb** [comment] 2024-03-18 07:24
It is indeed the symbol. But we don't have to remove it. A simple space or newline character would be a good workaround.
